name: CI

on: [push]

env:
  MAVEN_OPTS: -Xms64m -Xmx256m
  MAVEN_CLI_OPTS: -s .mvn/settings.xml -B
  MAVEN_GOALS: clean verify
  GITHUB_USER: fcrespel
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      run: mvn ${MAVEN_CLI_OPTS} ${MAVEN_GOALS} -DskipTests
    - name: Test
      run: mvn ${MAVEN_CLI_OPTS} test
    - name: Upload jar
      uses: actions/upload-artifact@v1
      with:
        name: jar
        path: target/runtastic-export-converter.jar
    - name: Upload jar-with-dependencies
      uses: actions/upload-artifact@v1
      with:
        name: jar-with-dependencies
        path: target/runtastic-export-converter-jar-with-dependencies.jar
    - name: Publish artifacts
      if: startsWith(github.ref, 'refs/tags')
      run: mvn ${MAVEN_CLI_OPTS} deploy -DskipTests
